{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "todolist.fullname" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: "roundrobin"
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: {{ include "todolist.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
  {{- if .Values.a_b_deploy.svc_name }}
  alternateBackends:
  - kind: Service
    name: {{ .Values.a_b_deploy.svc_name }}
    weight: {{ .Values.a_b_deploy.weight }}
  {{- end }}
status:
  ingress:
  - conditions:
    - status: 'True'
      type: Admitted
{{ end }}