apiVersion: v1
kind: Service
metadata:
  name: {{ include "plant-power.fullname" . }}
  labels:
    {{- include "plant-power.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "plant-power.selectorLabels" . | nindent 4 }}
