FROM registry.access.redhat.com/ubi8/nodejs-18

WORKDIR /opt/app-root/src

COPY package.json /opt/app-root/src/

RUN npm install --omit=dev

COPY server.js /opt/app-root/src/

EXPOSE 3000

CMD node server.js