{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "plant-server.fullname" . }}
  labels:
    {{- include "plant-server.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: "roundrobin"
spec:
  host: plant-server.{{ .Values.domain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "plant-server.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: 'True'
      type: Admitted
{{ end }}